version: 0.2
phases:
  install:
    commands:
      - echo Installing build dependencies
  build:
    commands:
      - echo Build started on `date`
      - mkdir -p output
      - cp index.html output/
artifacts:
  files:
    - output/**/* 
